### PR TITLE
[ASSIST-309] Application Health dashboard

### PR DESCRIPTION
**Pull request by mxm1070**
https://engage.canyongbs.com/workgroups/group/3/tasks/task/view/309/

### CODE REVIEW

**Review by Orrison — APPROVED** [review]
This looks good to me.

@dgoetzit I wanted to check to see if you are okay with merging this in for now being in the Laravel root.

I think we need to have a team meeting to go over:

- What we want to split into Modules.
- Work it into the sprint flow that this is thought of and decided on the ticket level
- Determine if we want a "core" Module, or treat root like "core", and then what things belong in there
- etc.

What are your thoughts?

**Review by Orrison — CHANGES_REQUESTED** [review]
@mxm1070 looks like there is a merge conflict here for `composer.lock`

Should be able to be resolved by rebasing on `develop`, picking one of the lock files, deleting `composer.lock`, then running `composer install` again. https://getcomposer.org/doc/articles/resolving-merge-conflicts.md

**Review by Orrison — APPROVED** [review]

**Review by Orrison — DISMISSED** [review]

**Review by Orrison — DISMISSED** [review]

**Comment by Orrison** [comment]
@mxm1070 there is something weird going on with this PR. Everytime I approve it it has either your User or my User dismiss it.

it also looks like it contains a bunch of changes that are already in `develop`.

I am wondering if perhaps the rebase went awry?

**Comment by mxm1070** [comment]
I read [here](https://github.com/orgs/community/discussions/58535) that maybe closing and opening would fix it so please try it again, if not I will manually remake the branch tomorrow.

**Comment by dgoetzit** [comment]
@ke

> This looks good to me.
> 
> @dgoetzit I wanted to check to see if you are okay with merging this in for now being in the Laravel root.
> 
> I think we need to have a team meeting to go over:
> 
> * What we want to split into Modules.
> * Work it into the sprint flow that this is thought of and decided on the ticket level
> * Determine if we want a "core" Module, or treat root like "core", and then what things belong in there
> * etc.
> 
> What are your thoughts?

I think this is a good approach for now. Let's get it in and then have those discussions.

**Review by Orrison — APPROVED** [review]

**Pull request merged**
